Failure # 1 (occurred at 2021-06-12_21-02-42)
Traceback (most recent call last):
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/worker.py", line 1494, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): [36mray::APEX.train_buffered()[39m (pid=20258, ip=192.168.100.8)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 608, in train
    raise e
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 74, in sampler
    yield workers.local_worker().sample()
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/jack/miniconda3/envs/dyno/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "auto_dyno_1d.py", line 186, in step
    obs_state = self.get_obs()
  File "auto_dyno_1d.py", line 261, in get_obs
    assert False, "This only works for 10 imgs, to not have many windows being opened"
AssertionError: This only works for 10 imgs, to not have many windows being opened

